keyboard_paths = ["/home/rick/keyboards"]
profile = "no_backup_test/v1.0"
log_level = "INFO"
disable_version_checks = true
deepdiff_delta_serializer = "json"
cache_path = "/custom/cache/path"
cache_strategy = "disabled"
cache_file_locking = true

[firmware.flash]
timeout = 150
count = 1
track_flashed = false
skip_existing = false
wait = true
poll_interval = 0.5
show_progress = true

[firmware.docker]
enable_user_mapping = false
detect_automatically = true
container_home_dir = "/custom/home"
force_manual = false
debug_user_mapping = false

[_metadata]
generated_at = "2025-06-19T00:00:30.161424"
glovebox_version = "unknown"
export_format = "toml"
include_defaults = true
