[project]
name = "glovebox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyobjc>=11.0 ; platform_system == 'Darwin'",
    "wmi>=1.5.1 ; platform_system == 'Windows'",
]

[dependency-groups]
dev = [
    "aider-chat>=0.81.0",
    "google-genai>=1.9.0",
]
