# ZMK Bluetooth Behaviors - Bluetooth management behaviors
behaviors:
  system_behaviors:
    - code: "&bt"
      name: "Bluetooth"
      description: "The Bluetooth behavior allows management of various settings and states related to the bluetooth connection(s) between the keyboard and the host."
      url: "https://zmk.dev/docs/behaviors/bluetooth"
      isMacroControlBehavior: false
      expected_params: 1
      origin: "zmk"
      params:
        - "command"
      includes:
        - "dt-bindings/zmk/bt.h"
      commands:
        - code: "BT_CLR"
          description: "Clear bond information between the keyboard and host for the selected profile."
        - code: "BT_CLR_ALL"
          description: "Clear bond information between the keyboard and host for *all* profiles."
        - code: "BT_NXT"
          description: "Switch to the next profile, cycling through to the first one when the end is reached."
        - code: "BT_PRV"
          description: "Switch to the previous profile, cycling through to the last one when the beginning is reached."
        - code: "BT_DISC"
          description: "[Beta-PR25 and newer] Disconnect from the 0-indexed profile by number, if it's currently connected and inactive. Please note: this definition must include a number as an argument in the keymap to work correctly. eg. `BT_DISC 0`"
          flatten: true
          additionalParams:
            - name: "Bluetooth Profile"
              type: "enum"
              values:
                - 0
                - 1
                - 2
                - 3
                - 4
        - code: "BT_SEL"
          description: "Do not use this unless you are defining a macro; use &bt_0 to &bt_3 instead. Select the 0-indexed profile by number. Please note: this definition must include a number as an argument in the keymap to work correctly. eg. BT_SEL 0"
          flatten: true
          additionalParams:
            - name: "Bluetooth Profile"
              type: "enum"
              values:
                - 0
                - 1
                - 2
                - 3
                - 4

    - code: "&out"
      name: "Output Selection"
      description: "Allows selecting whether keyboard output is sent to the USB or bluetooth connection when both are connected."
      url: "https://zmk.dev/docs/behaviors/outputs"
      isMacroControlBehavior: false
      expected_params: 1
      origin: "zmk"
      params:
        - "command"
      includes:
        - "dt-bindings/zmk/outputs.h"
      commands:
        - code: "OUT_BLE"
          description: "Prefer sending to the current bluetooth profile"
        - code: "OUT_USB"
          description: "Prefer sending to USB"
        - code: "OUT_TOG"
          description: "Toggle between USB and BLE"